### PR TITLE
Add PK ordering when don't have any ordering

### PR DESCRIPTION
**Pull request by ebertti**

### CODE REVIEW

**Comment by gregplaysguitar** [comment]
Hi, I'm already adding pk here: https://github.com/gregplaysguitar/django-next-prev/blob/master/next_prev.py#L48

Is that not working for you?

**Comment by ebertti** [comment]
No. 

next_prev.py#L48 just made work on query, not for ordering

**Comment by gregplaysguitar** [comment]
Hmm, ok. Do you mind writing a test case for this? Or, if you're not comfortable doing that, can you provide some sample code that demonstrates the issue?

**Comment by gregplaysguitar** [comment]
Actually - have a look at 4337a5649b7443326b79faf06d26e64d9cdb4e0e and let me know if that solves your problem?

**Pull request closed without merging**
